(() => {
  'use strict';
  const STORAGE_KEY = 'recall-reviewers-v1';
  const state = { reviewers: loadReviewers(), activeId: null, session: null, questionIndex: 0, answers: {}, checked: false, sourceText: '', selectedFile: null };
  const NAV_KEY = 'rev-sidebar-open';
  const THEME_KEY = 'rev-theme';
  const $ = (s, root = document) => root.querySelector(s);
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone = value => JSON.parse(JSON.stringify(value));
  function loadReviewers() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); } catch { return []; } }
  function saveReviewers() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.reviewers)); } catch { toast('Storage is full. Export this reviewer to keep a backup.'); } }
  function toast(message) { const el = document.createElement('div'); el.className='toast'; el.textContent=message; document.body.append(el); setTimeout(()=>el.remove(),2600); }
  function parseReviewer(text) {
    const lines = String(text).replace(/\r/g,'').replace(/\u200b/g,'').split('\n');
    const questions=[]; let current=null; let inQuestion=false;
    const dropPageCarry=(items)=>{while(items.length&&/^\\nQuestion\s*\d+\b/i.test(items[items.length-1]))items.pop();};
    const flush=()=>{ if (!current) return; current.text=current.textParts.join('\n').trim(); delete current.textParts; current.options=current.options.map(o=>o.text.trim()).filter(Boolean); current.correctAnswers=current.options.map((o,i)=>current.correctFlags[i]?i:-1).filter(i=>i>=0); current.type=current.options.length ? (current.options.length===2 && /^(true|false)$/i.test(current.options.join('')) ? 'boolean' : 'choice') : 'text'; if(current.text || current.options.length) questions.push(current); current=null; inQuestion=false; };
    for (const original of lines) {
      const line=original.trim();
      if (/^Question\s*\d+\b/i.test(line)) { flush(); current={textParts:[],options:[],correctFlags:[],sourceNumber:(line.match(/\d+/)||[])[0]}; inQuestion=true; continue; }
      if (!current) { if (!line) continue; current={textParts:[],options:[],correctFlags:[],sourceNumber:String(questions.length+1)}; inQuestion=true; }
      if (/^\d+$/.test(line) && Number(line) <= 54 && !inQuestion) continue;
      const scoredMatch=line.match(/^(.*?)\s*\((correct|wrong)\)$/i);
      if(scoredMatch){const answerText=scoredMatch[1].trim();if(/\bYou Answered\b/i.test(answerText)){current.textParts.push(answerText);}else{current.options.push({text:answerText});current.correctFlags.push(scoredMatch[2].toLowerCase()==='correct');}inQuestion=false;continue;}
      const correctMatch=line.match(/^Correct!\s*(.*)$/i);
      if (correctMatch) { if(current.textParts.length){const tail=current.textParts.pop();if(tail){current.options.push({text:tail});current.correctFlags.push(false);}}current.options.push({text:correctMatch[1]}); current.correctFlags.push(true); inQuestion=false; continue; }
      if (/^\\nQuestion\s*\d+\b/i.test(line)) { dropPageCarry(current.options);dropPageCarry(current.textParts);flush(); current={textParts:[],options:[],correctFlags:[],sourceNumber:(line.match(/\d+/)||[])[0]}; inQuestion=true; continue; }
      if (!inQuestion && line) { current.options.push({text:line}); current.correctFlags.push(false); continue; }
      if (inQuestion) { if(line)current.textParts.push(line); else if(current.textParts.length)current.textParts.push(''); }
    }
    flush();
    return questions;
  }
  function renderLibrary() {
    const list=$('#reviewer-list');
    list.innerHTML=state.reviewers.length ? state.reviewers.map(r=>`<button class="reviewer-item ${r.id===state.activeId?'active':''}" data-reviewer="${escapeHtml(r.id)}"><span class="file-icon">▤</span><span style="min-width:0"><span class="reviewer-title">${escapeHtml(r.title)}</span><span class="reviewer-meta">${r.questions.length} questions</span></span><span class="reviewer-delete" data-delete="${escapeHtml(r.id)}" title="Delete reviewer" aria-label="Delete reviewer">×</span></button>`).join('') : '<p class="empty-list">Your reviewers will appear here.</p>';
    list.querySelectorAll('[data-reviewer]').forEach(btn=>btn.addEventListener('click', e=>{if(e.target.closest('[data-delete]'))return;openReviewer(btn.dataset.reviewer);}));
    list.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();deleteReviewer(btn.dataset.delete);}));
  }
  function deleteReviewer(id) { state.reviewers=state.reviewers.filter(r=>r.id!==id);if(state.activeId===id){state.activeId=null;state.session=null;renderMain();}saveReviewers();renderLibrary(); }
  function activeReviewer(){return state.reviewers.find(r=>r.id===state.activeId);}
  function openReviewer(id){state.activeId=id;state.session=null;state.answers={};state.questionIndex=0;renderLibrary();renderMain();}
  function renderMain(){const panel=$('#main-panel'),reviewer=activeReviewer(),intro=$('#intro');const studying=Boolean(reviewer&&state.session&&state.session!=='results');document.body.classList.toggle('is-studying',studying);intro.hidden=studying;if(!reviewer){panel.innerHTML=`<div class="welcome"><div class="welcome-inner"><div class="welcome-symbol">✎</div><h2>Your next “I know this” starts here.</h2><p>Add a reviewer to build a focused quiz. Your progress stays on this device.</p><button class="primary-button" id="welcome-import">Add a reviewer <span>→</span></button></div></div>`;$('#welcome-import').onclick=openImport;return;}if(!state.session){const count=reviewer.questions.length;panel.innerHTML=`<div class="welcome"><div class="welcome-inner"><div class="welcome-symbol">▤</div><h2>${escapeHtml(reviewer.title)}</h2><p>${count} questions, ready when you are.<br>Questions stay in source order. Correct answers keep their original option positions.</p><button class="primary-button" id="start-quiz" ${count?'':'disabled'}>Start reviewing <span>→</span></button><div style="margin-top:15px"><button class="mini-control" id="export-reviewer">Export reviewer</button><button class="mini-control" id="edit-reviewer">Edit questions</button></div></div></div>`;$('#start-quiz').onclick=()=>startQuiz(false);$('#export-reviewer').onclick=()=>exportReviewer(reviewer);$('#edit-reviewer').onclick=editReviewer;return;}if(state.session==='results'){renderResults();return;}renderQuestion();}
  function startQuiz(shuffle){const r=activeReviewer();if(!r)return;let order=r.questions.map((_,i)=>i);if(shuffle)for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}state.session=order;state.questionIndex=0;state.answers={};state.checked=false;renderMain();}
  function currentQuestion(){const r=activeReviewer();return r?.questions[state.session[state.questionIndex]];}
  function renderQuestion(){const q=currentQuestion(),r=activeReviewer(),n=state.questionIndex+1,total=state.session.length;const pct=Math.round((n-1)/total*100);let controls='';if(q.options?.length){const multi=q.correctAnswers.length>1;controls=`<div class="answer-list">${q.options.map((o,i)=>{const selected=(state.answers[n]||[]).includes(i),correct=q.correctAnswers.includes(i);let cls=selected?'selected':'';if(state.checked){cls=correct?'correct':selected?'incorrect':'';}return `<button class="answer-option ${cls}" data-option="${i}" ${state.checked?'disabled':''}><span class="option-letter">${multi?'✓':String.fromCharCode(65+i)}</span><span>${escapeHtml(o)}</span></button>`;}).join('')}</div>`;}else controls=`<input class="short-answer" id="short-answer" type="text" autocomplete="off" placeholder="Type your answer…" value="${escapeHtml((state.answers[n]||[])[0]??'')}" ${state.checked?'disabled':''}>`;
    const selected=(state.answers[n]||[]);let feedback='';if(state.checked){const isCorrect=q.options?.length?sameSet(selected,q.correctAnswers):normalizeAnswer(selected[0]||'')===normalizeAnswer(q.answer||'');feedback=`<span class="feedback ${isCorrect?'good':'bad'}">${isCorrect?'Nice work — that’s right.':`Not quite. Answer: ${escapeHtml(q.correctAnswers.map(i=>q.options[i]).join(', ')||q.answer||'')}`}</span>`;}
    $('#main-panel').innerHTML=`<div class="study-head"><div class="study-label"><span class="study-chip">${escapeHtml(r.title)}</span><span>${q.options?.length?(q.correctAnswers.length>1?'Select all that apply':'Choose one'):'Fill in the answer'}</span></div><div class="study-controls"><button class="mini-control" id="shuffle-questions">↻ Shuffle questions</button><button class="mini-control" id="exit-quiz">Exit review</button></div></div><div class="progress-row"><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><span class="progress-copy">${n} of ${total}</span></div><article class="question-card"><div class="question-number">QUESTION ${n}</div><div class="question-text">${escapeHtml(q.text)}</div>${q.image?`<img class="question-image" src="${escapeHtml(q.image)}" alt="Question exhibit">`:''}</article>${controls}<div class="question-footer"><div>${feedback}</div><div class="nav-buttons"><button class="secondary-button" id="prev-question" ${state.questionIndex===0?'disabled':''}>← Back</button>${state.checked?`<button class="primary-button" id="next-question">${n===total?'See results':'Continue'} <span>→</span></button>`:`<button class="primary-button" id="check-answer" ${selected.length?'':'disabled'}>Check answer <span>→</span></button>`}</div></div>`;
    $('#main-panel').querySelectorAll('[data-option]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.option);let a=state.answers[n]||[];if(q.correctAnswers.length>1){a=a.includes(i)?a.filter(x=>x!==i):[...a,i];}else a=[i];state.answers[n]=a;renderQuestion();});const short=$('#short-answer');if(short)short.oninput=()=>{state.answers[n]=short.value? [short.value]:[];$('#check-answer').disabled=!short.value.trim();};const check=$('#check-answer');if(check)check.onclick=()=>{if(!selected.length)return;state.checked=true;renderQuestion();};$('#prev-question').onclick=()=>moveQuestion(-1);const next=$('#next-question');if(next)next.onclick=()=>{if(state.questionIndex===total-1){state.session='results';renderMain();}else moveQuestion(1);};$('#exit-quiz').onclick=()=>{state.session=null;renderMain();};$('#shuffle-questions').onclick=()=>{startQuiz(true);toast('Question order shuffled.');};
  }
  function sameSet(a,b){return a.length===b.length&&a.every(x=>b.includes(x));}
  function normalizeAnswer(s){return String(s).toLowerCase().trim().replace(/[.,!?;:]$/,'').replace(/\s+/g,' ');}
  function moveQuestion(delta){state.questionIndex=Math.min(state.session.length-1,Math.max(0,state.questionIndex+delta));state.checked=Boolean(state.answers[state.questionIndex+1]?.__checked);renderQuestion();}
  function renderResults(){const r=activeReviewer();let score=0;const rows=state.session.map((qi,i)=>{const q=r.questions[qi],a=state.answers[i+1]||[],ok=q.options?.length?sameSet(a,q.correctAnswers):normalizeAnswer(a[0]||'')===normalizeAnswer(q.answer||'');if(ok)score++;return {q,ok,a};});$('#main-panel').innerHTML=`<div class="result-view"><div><div class="welcome-symbol">✦</div><h2 class="result-title">Review complete.</h2><div class="result-score">${score}<span style="font-size:22px;color:#a3a4ac"> / ${rows.length}</span></div><p class="result-sub">${score===rows.length?'Every answer, right on recall.':score===0?'A fresh pass is a good place to start.':'A little more practice and you’ll have it.'}</p><div class="result-actions"><button class="secondary-button" id="back-to-reviewer">Done</button><button class="primary-button" id="retry-quiz">Review again <span>→</span></button></div><div class="review-list">${rows.map((x,i)=>`<div class="review-row"><span>${i+1}. ${escapeHtml(x.q.text.slice(0,75))}${x.q.text.length>75?'…':''}</span><span style="color:${x.ok?'#39845e':'#c45b60'}">${x.ok?'Correct':'Review'}</span></div>`).join('')}</div></div></div>`;$('#back-to-reviewer').onclick=()=>{state.session=null;renderMain();};$('#retry-quiz').onclick=()=>startQuiz(false);}
  function exportReviewer(r){const blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json'});download(blob,`${safeName(r.title)}.json`);}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function safeName(s){return String(s).replace(/[^a-z0-9-_]+/gi,'-').replace(/^-|-$/g,'').slice(0,60)||'reviewer';}
  function editReviewer(){const r=activeReviewer();if(!r)return;const text=reviewerToText(r);$('#paste-text').value=text;$('#import-dialog').dataset.editId=r.id;openImport();}
  function reviewerToText(r){return r.questions.map((q,i)=>`Question ${i+1}\n${q.text}\n${q.options?.length?q.options.map((o,j)=>`${q.correctAnswers.includes(j)?'Correct! ':''}${o}`).join('\n'):q.answer||''}`).join('\n\n');}
  function openImport(){const d=$('#import-dialog');delete d.dataset.editId;state.sourceText='';state.selectedFile=null;$('#paste-text').value='';$('#file-status').textContent='PDF text is extracted locally in your browser.';showImportTab('paste');d.showModal();}
  function showImportTab(tab){document.querySelectorAll('.import-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#paste-pane').hidden=tab!=='paste';$('#file-pane').hidden=tab!=='file';}
  function addReviewer(text,title,editId){const questions=parseReviewer(text);if(!questions.length){toast('No questions found. Check the question formatting and try again.');return;}const reviewer={id:editId||crypto.randomUUID(),title:(title||'New reviewer').replace(/\.(pdf|txt|md)$/i,'').slice(0,70),questions,updatedAt:Date.now()};if(editId){const i=state.reviewers.findIndex(r=>r.id===editId);if(i>=0)state.reviewers[i]=reviewer;else state.reviewers.push(reviewer);}else state.reviewers.unshift(reviewer);state.activeId=reviewer.id;state.session=null;saveReviewers();renderLibrary();renderMain();$('#import-dialog').close();toast(`${questions.length} questions added.`);}
  async function extractFile(file){if(!file)return;state.selectedFile=file;$('#file-status').textContent=`Selected: ${file.name}`;if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){if(!window.pdfjsLib){toast('PDF reader could not load. Use the built-in PDF text viewer and paste its text.');return;}window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const data=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjsLib.getDocument({data}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();pages.push(content.items.map(x=>x.str).join(' '));}state.sourceText=pages.join('\n');$('#file-status').textContent=`Ready: ${file.name} · ${pdf.numPages} pages extracted`;toast('PDF text extracted.');}else{state.sourceText=await file.text();$('#file-status').textContent=`Ready: ${file.name}`;}}
  function init(){if(!state.reviewers.length&&window.RECALL_STARTER_REVIEWER){state.reviewers=[clone(window.RECALL_STARTER_REVIEWER)];saveReviewers();}document.body.classList.toggle('sidebar-collapsed',localStorage.getItem(NAV_KEY)==='false');document.body.classList.toggle('dark',localStorage.getItem(THEME_KEY)==='dark');syncThemeLabel();renderLibrary();renderMain();$('#sidebar-toggle').onclick=()=>{const collapsed=document.body.classList.toggle('sidebar-collapsed');localStorage.setItem(NAV_KEY,String(!collapsed));$('#sidebar-toggle').setAttribute('aria-label',collapsed?'Expand navigation':'Collapse navigation');$('#sidebar-toggle').title=collapsed?'Expand navigation':'Collapse navigation';};$('#new-reviewer').onclick=openImport;$('#import-trigger').onclick=openImport;$('#cancel-import').onclick=()=>$('#import-dialog').close();document.querySelectorAll('.import-tab').forEach(b=>b.onclick=()=>showImportTab(b.dataset.tab));$('#file-input').onchange=()=>extractFile($('#file-input').files[0]).catch(e=>{console.error(e);toast('Could not read this file.');});$('#import-submit').onclick=()=>{const d=$('#import-dialog'),file=state.selectedFile;const text=$('#paste-pane').hidden?state.sourceText:$('#paste-text').value;if(!text.trim()){toast('Choose a file or paste your reviewer first.');return;}const title=file?.name||'New reviewer';addReviewer(text,title,d.dataset.editId);};$('#theme-toggle').onclick=()=>{const dark=document.body.classList.toggle('dark');localStorage.setItem(THEME_KEY,dark?'dark':'light');syncThemeLabel();};}
  function syncThemeLabel(){const dark=document.body.classList.contains('dark');$('#theme-state').textContent=dark?'Dark':'Light';$('#theme-toggle').setAttribute('aria-label',`Switch to ${dark?'light':'dark'} mode`);}
  init();
})();
